project_name: photo_review_cls_prt
train_set: train
val_set: val
test_set: eval
num_classes: 3

test_ratio: 0.2
random_seed: 512

model_name: efficientnet-b3
coef: 3
batch_size: 32
num_epochs: 50
input_size: 300
lr: 0.0005
weight_decay: 0.0001
momentum: 0.9
loss_fn: cross_entropy
optm_fn: sgdp
lr_scheduler: mp
patience: 3
min_delta: 0.001

# coco dataset
mean: [ 0.485, 0.456, 0.406 ]
std: [ 0.229, 0.224, 0.225 ]

# dataset info
data_root: data/220719/dataset
class_list: ["00_best","10_normal","20_bad"]
