project_name: photo_review_cls_prt
train_set: train
val_set: val
test_set: test
num_classes: 3

test_ratio: 0.2
random_seed: 512

model_name: vggnet16
batch_size: 16
num_epochs: 10
input_size: 224
lr: 0.0001
weight_decay: 0
loss_fn: cross_entropy
optm_fn: sgd
lr_scheduler: cosine_an

# coco dataset
mean: [ 0.485, 0.456, 0.406 ]
std: [ 0.229, 0.224, 0.225 ]

data_root: data/dataset
class_list: ["0_best","1_normal","2_bad"]
